### ISSUE TITLE
animal barns that have auto water filing need water

### ISSUE THREAD

**Issue by bunkeris30** [4c65736975/additionalUnits#9]
so i had this issue that now if an animal barn doesn't need to get filled with water and doesn't have anywhere to fill it in the menu it still shows that they need water, and now i can't have any animals. I've searched thru every mod and I am sure that additional units is the mod that does this

**Comment by Caamo** [comment]
This is true.
Animal pens NOT using water, will have useless water need level, which you can't support, because there is no water intake at all.
So we can't use this mod in maps like Castelnaud etc...

**Comment by 4c65736975** [comment]
Already fixed, you have to wait for upcoming update, soon on github.

**Comment by Caamo** [comment]
Oh, ok. That's cool, thank you very much!

**Comment by bunkeris30** [comment]
> Already fixed, you have to wait for upcoming update, soon on github.

when will we get that update? or could you tell us how to fix the mod ourselves?
